dev:
  outputs:
    stage:
      dataset: stage
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile:  your_service_account.json # add your service account path  
      location: US
      method: service-account
      priority: interactive
      project: your-project-id
      threads: 10
      type: bigquery
    data_model:
      dataset: data_model
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: your_service_account.json # add your service account path  
      location: US
      method: service-account
      priority: interactive
      project: your-project-id
      threads: 10
      type: bigquery
  target:  stage